### PR TITLE
Avoid delete cr issue from prettier

### PR DESCRIPTION
**Pull request by jcs090218**
I am getting this error

https://stackoverflow.com/questions/53516594/why-do-i-keep-getting-delete-cr-prettier-prettier

Add this avoid delete cr.

### CODE REVIEW

**Comment by nanochromatic** [comment]
Do the files have CRLF (Windows) line endings when checking out the repo through Git? If so, you will see the Prettier error for Delete CR.

**Comment by jcs090218** [comment]
Yes, I am on Windows machine. I wonder why not just handle the line endings automatically? 😕

**Comment by nanochromatic** [comment]
I'd like to enforce the Prettier rule in case there are inconsistencies for eol on commits. If Git's `core.autocrlf` option is changed to `false`, CRLF is not converted to LF when committing.

I added a `.gitattributes` file to the repo, which will enforce LF line endings on a new checkout. Can you try cloning the repo again to see if it works? This should also resolve the issue you're seeing with Delete CR.

**Comment by jcs090218** [comment]
It works! Thank you! :)

**Pull request closed without merging**
